-- IF NOT EXISTS (SELECT * FROM pg_user WHERE username = 'airflow')
-- BEGIN
--         CREATE USER airflow WITH PASSWORD 'airflow';
--         GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;
-- END;